/**
 * AortaLink On-Device Clinical ML — Engine Orchestrator
 * -----------------------------------------------------
 * Runs every on-device model over the user's real records and produces one
 * report. Narratives ("insights") are generated by deterministic rules whose
 * every sentence traces back to a computed number — no generative AI, no
 * invented conclusions, no network calls.
 */

import { BPReading, CircadianDippingReport, LabResult, MedicationItem, MedicationLog, Profile, SleepLog, SodiumLog } from '../../types/blood-pressure';
import { calculateNocturnalDipping } from '../../utils/advanced-analytics';
import { forecastBpTrend, type BpTrendForecast } from './trend-forecaster';
import { detectBpPatterns, type BpPatternFinding } from './pattern-detector';
import { analyzeAdherenceImpact, type AdherenceAnalysis } from './adherence-model';

export const ML_ENGINE_VERSION = '1.0.0';

export type InsightPriority = 'critical' | 'warning' | 'positive' | 'info';

export interface MlInsight {
  id: string;
  priority: InsightPriority;
  title: string;
  body: string;
}

export interface ClinicalMlReport {
  generatedAt: string;
  engineVersion: string;
  dataSummary: {
    profileName: string;
    totalReadings: number;
    spanDays: number;
    scheduledMedications: number;
    labResults: number;
  };
  trend: BpTrendForecast;
  patterns: BpPatternFinding[];
  dipping: CircadianDippingReport | null;
  adherence: AdherenceAnalysis;
  insights: MlInsight[];
  disclaimer: string;
}

export interface ClinicalMlInput {
  profile: Profile | null;
  readings: BPReading[];
  medications: MedicationItem[];
  medicationLogs: MedicationLog[];
  sodiumLogs: SodiumLog[];
  sleepLogs: SleepLog[];
  labResults: LabResult[];
}

export const ML_DISCLAIMER =
  'Analisis dihasilkan mesin statistik on-device dari data Anda sendiri — bukan diagnosis. Keputusan terapi selalu bersama dokter.';

export function runClinicalMlAnalysis(input: ClinicalMlInput): ClinicalMlReport {
  const { profile, readings, medications, medicationLogs, sodiumLogs, sleepLogs, labResults } = input;

  const trend = forecastBpTrend(readings);
  const patterns = detectBpPatterns(readings);
  const dipping = readings.length >= 3 ? calculateNocturnalDipping(readings) : null;
  const adherence = analyzeAdherenceImpact({
    medications,
    medicationLogs,
    readings,
    sodiumLogs,
    sleepLogs,
    targetSystolic: profile?.targetSystolic || 120,
    targetDiastolic: profile?.targetDiastolic || 80
  });

  const insights = buildInsights({ profile, readings, trend, patterns, dipping, adherence, labResults });

  const latest = [...readings].sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  )[0];

  return {
    generatedAt: new Date().toISOString(),
    engineVersion: ML_ENGINE_VERSION,
    dataSummary: {
      profileName: profile?.name || 'Profil',
      totalReadings: readings.length,
      spanDays: trend.spanDays,
      scheduledMedications: medications.filter((m) => m.schedule !== 'sesuai_kebutuhan').length,
      labResults: labResults.length
    },
    trend,
    patterns,
    dipping,
    adherence,
    insights,
    disclaimer: ML_DISCLAIMER
  };
}

interface InsightContext {
  profile: Profile | null;
  readings: BPReading[];
  trend: BpTrendForecast;
  patterns: BpPatternFinding[];
  dipping: CircadianDippingReport | null;
  adherence: AdherenceAnalysis;
  labResults: LabResult[];
}

function buildInsights(ctx: InsightContext): MlInsight[] {
  const { readings, trend, patterns, dipping, adherence, profile } = ctx;
  const insights: MlInsight[] = [];

  // 0 readings → single honest onboarding insight.
  if (readings.length === 0) {
    insights.push({
      id: 'no-data',
      priority: 'info',
      title: 'Mesin analisis menunggu data asli Anda',
      body: 'Semua model di AortaLink belajar dari pengukuran yang Anda catat sendiri. Catat pengukuran pertama, dan tren, pola, serta estimasi kepatuhan akan terisi otomatis — tanpa data contoh, tanpa angka palsu.'
    });
    return insights;
  }

  // 1. Crisis — latest reading in hypertensive crisis range.
  const latest = [...readings].sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  )[0];
  if (latest.systolic >= 180 || latest.diastolic >= 120) {
    insights.push({
      id: 'crisis',
      priority: 'critical',
      title: 'Pengukuran terakhir berada di zona krisis',
      body: `Terukur ${latest.systolic}/${latest.diastolic} mmHg. Angka ini berada di ambang krisis hipertensi (≥180/120). Jika disertai gejala seperti nyeri dada, sesak napas, penglihatan kabur, atau bicara pelan, segera cari pertolongan medis — jangan menunggu pengukuran berikutnya.`
    });
  }

  // 2. Trend.
  if (trend.sufficientData && trend.isClinicallySignificant) {
    insights.push({
      id: 'trend-significant',
      priority: trend.direction === 'rising' ? 'warning' : 'positive',
      title: trend.direction === 'rising' ? 'Tren tekanan darah naik bermakna' : 'Tren tekanan darah membaik',
      body: trend.assessment
    });
  }

  // 3. Dipping pattern (needs day+night spread of readings).
  if (dipping && (dipping.pattern === 'riser' || dipping.pattern === 'non_dipper')) {
    insights.push({
      id: 'dipping',
      priority: 'warning',
      title: `Pola malam Anda: ${dipping.label}`,
      body: dipping.description
    });
  }

  // 4. Patterns worth surfacing.
  const significantPatterns = patterns.filter((p) => p.strength === 'significant' && p.detected);
  for (const pattern of significantPatterns.slice(0, 2)) {
    insights.push({
      id: `pattern-${pattern.key}`,
      priority: pattern.key === 'masked_hypertension' ? 'warning' : 'info',
      title: pattern.label,
      body: pattern.interpretation
    });
  }

  // 5. Adherence.
  if (adherence.sufficientData) {
    if (adherence.adherenceRate !== null && adherence.adherenceRate < 0.7) {
      insights.push({
        id: 'adherence-low',
        priority: 'warning',
        title: 'Kepatuhan obat rendah',
        body: adherence.assessment
      });
    } else {
      insights.push({
        id: 'adherence-model',
        priority: 'info',
        title: 'Model kepatuhan aktif',
        body: adherence.assessment
      });
    }
  }

  // 6. Positive reinforcement when genuinely controlled.
  const targetSys = profile?.targetSystolic || 120;
  const targetDia = profile?.targetDiastolic || 80;
  const controlledShare = adherence.controlledDaysShare;
  if (
    controlledShare !== null &&
    controlledShare >= 0.8 &&
    !(trend.isClinicallySignificant && trend.direction === 'rising')
  ) {
    insights.push({
      id: 'controlled',
      priority: 'positive',
      title: 'Kontrol tekanan darah Anda baik',
      body: `Target ≤${targetSys}/${targetDia} tercapai pada ${Math.round(controlledShare * 100)}% hari pengukuran. Pertahankan regimen, jadwal ukur, dan gaya hidup yang sedang berjalan.`
    });
  }

  return insights;
}
